feat(STOCK-19) добавлен эндпоинт для выгрузки статистики по всем пользователям в excel
vladdossik/lissa-trading-statistics-service pull request #1
Opened 2024-10-24 18:16 UTC by SashaTyutyaev

2024-10-24 18:42 UTC, kenpxrk1 commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
https://habr.com/ru/articles/579178/

2024-10-25 08:05 UTC, Belaquaa requested changes

2024-10-25 08:05 UTC, Belaquaa commented on .gitignore
> +HELP.md
Оставь только для Интеллижи гитигнор, можешь посмотреть, какой он в других сервисах проекта

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +        Workbook workbook = new XSSFWorkbook();
Посмотри, что лучше: SXSSFWorkbook или XSSFWorkbook

SXSSFWorkbook намного лучше работает с памятью, что полезно для больших отчётов

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +        log.info("Successfully generated user data");
у тебя тут будет миллион логов, вынеси из цикла

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +                workbook.close();
будто можно в самом начале сделать try (Workbook workbook = new SXSSFWorkbook()) {...}

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +            if (value instanceof Double) {
Здесь правильно написал Дима, лучше через switch-case сделать

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +            } catch (IOException e) {
у тебя при ошибке клиент ничего не получит в ответ. Посмотри, как через response.setStatus() можно это сделать

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/controller/UserReportController.java
> +    public void getUsersReport(HttpServletResponse response) throws IOException {
throws IOEx... надо убрать, ты же ловишь ошибку в своем методе сервиса 

когда ты так пишешь, обработку исключения ты передаешь фреймворку -> клиент может не получить ошибку (либо получит стандартную 500 без доп. инфы)

Тут дополнительно можешь почитать про глобальный обработчик исключений. Но я бы все-таки оставил обработку внутри сервиса

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/utils/UserExcelMappingUtil.java
> +    public static final String TODAY_DATE = FORMATTER.format(LocalDateTime.now());
точно такие модификаторы?

когда инициализируются переменные static final? какая дата будет в отчетах?

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/utils/UserExcelMappingUtil.java
> +@Component
нужна ли аннотация @Component для создания бинов, если все поля static final?

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/utils/UserExcelMappingUtil.java
> +    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH.mm");
Методы и константы располагаются так: сначала private, после public

2024-10-25 08:05 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +    private void createHeaders(Sheet sheet) {
у тебя каждый раз при генерации отчета создаются стили

можно ли создать стили один раз и их переиспользовать?

2024-10-25 08:12 UTC, kenpxrk1 commented on src/main/java/lissa/trading/statisticsService/utils/UserExcelMappingUtil.java
> +    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH.mm");
Не согласен, Влад говорил, что наоборот, для удобности чтения паблики выше приватных

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/model/User.java
> +public class User {
сущность точно будет переделываться из такого вида в вид типа 
id, externalId, jsonB(full object)

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +import static lissa.trading.statisticsService.utils.UserExcelMappingUtil.*;
* надо убрать

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +    public void generateExcelReport(HttpServletResponse response) {
@Transactional(readOnly = true)

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +        int rowCount = 1;
1 это же константа -> наверх

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +                "attachment; filename=users_report " + TODAY_DATE + ".xlsx");
название файла на русском

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +        for (int i = 0; i < GETTERS_LIST.size(); i++) {
название списка хуевое какое-то

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/utils/UserExcelMappingUtil.java
> +@Component
не нужна

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/utils/UserExcelMappingUtil.java
> +    public static final List<String> COLUMN_NAMES = List.of(
ой пиздец

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/utils/UserExcelMappingUtil.java
> +    public static final List<String> COLUMN_NAMES = List.of(
у тебя че 2 списка и единственное как их можно соотнести это по индексу??

надо переделать этот момент на 1 список общий

2024-10-25 08:13 UTC, vladdossik commented on src/main/java/lissa/trading/statisticsService/utils/UserExcelMappingUtil.java
> +    public static final List<String> COLUMN_NAMES = List.of(
название для этого класса можно сделать UserExportExcelColumns

2024-10-25 08:27 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/utils/UserExcelMappingUtil.java
> +    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH.mm");
Ой, наоборот, конечно

2024-10-25 08:29 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +import static lissa.trading.statisticsService.utils.UserExcelMappingUtil.*;
Это можно в настройках ставить, чтобы не ставились звёздочки никогда

И через пвтоформатирование оно будет разъединяться (Ctrl + alt + L)

2024-10-25 08:48 UTC, SashaTyutyaev commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +        log.info("Successfully generated user data");
Он же уже за циклом
У меня только 1 лог появляется при создании

2024-10-25 09:10 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +        log.info("Successfully generated user data");
for (UserReportDto user : users) {
            Row row = sheet.createRow(rowCount++);
            writeUserData(user, row);
}
        
У тебя этот метод в цикле вызывается, а логирование как раз в нем

2024-10-25 16:27 UTC, SashaTyutyaev commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +    private void createHeaders(Sheet sheet) {
Что ты имеешь ввиду под стилями? CellStyle? Я думал, пытался вынести это как то в отдельный метод, но чтобы создать CellStyle нам нужен Sheet, чтобы создать Sheet нам нужен Workbook. По идее каждый отчет это новый workbook(в моем понимании). Я попытался сделать в @PostConstruct методе, но нам нужен каждый раз новый workbook, и надо было бы делать тогда бин со скоупом prototype, что показалось мне слишком сложным. А если ты говоришь про сам метод, то тут я тоже не понимаю как вынести его куда то. Все сводится к тому, что каждый раз надо заново создавать workbook и sheet, и потом уже в каждой новой sheet вставлять в ячейки значения.

2024-10-25 23:11 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/exceptions/ErrorResponse.java
> +    public ErrorResponse(String error) {
@AllArgsConstructor

2024-10-25 23:11 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +        Sheet sheet;
Можно перенести в сам метод
и делать внутри него 
Sheet sheet = workbook.createSheet("Отчет по пользователям");

2024-10-25 23:11 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +            for (UserReportDto user : users) {
*необязательные изменения*
если хочешь, можешь попробовать сделать обычный цикл for (int i = 0; i < users.size(); i++) {}, чтобы убрать непонятную переменную int rowCount = 1;

2024-10-25 23:11 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +                default -> cell.setCellValue(value.toString());
А может здесь быть null? У него нет метода toString, будет ошибка 
И может ли сюда попасть LocalDateTime?

я бы сделал в таком случае что-то типа default -> cell.setCellValue("") после проверок на все возможное

2024-10-25 23:11 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/utils/columns/TextColumn.java
> +    private Function<T, Object> columnValue;
здесь можно даже написать private Function<T, String> columnValue, т.к. ты используешь только строки

также можно добавить везде final

2024-10-25 23:11 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/utils/columns/NumericColumn.java
> +    private String columnName;
final в полях

2024-10-25 23:16 UTC, SashaTyutyaev commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +                default -> cell.setCellValue(value.toString());
LocalDateTime не должен попасть, потому что я сразу ее форматирую в строку в списке колонок. А вот с null ты прав

2024-10-28 07:26 UTC, vladdossik commented
оставлю все комменты сразу тут

1) ликвибейз настроен неправильно, нужно чтобы во всех наших сервисах была 1 и та же реализация. Посмотри и исправь

2) в урле должно быть вначале /v1

3) Исходя из того, что мы решили, что будет несколько реализаций для выгрузки отчетов я не вижу как ты будешь использовать потом свой excelService
ведь если я скажу добавить еще один отчет, то тебе нужно будет менять текущую реализацию
как будто бы уже сейчас стоит добавить @Qualifier и использовать бины по имени

4) пакет exceptions -> exception

5) необходимо к полям датам в дто добавить формат этих дат
у энтити этого делать не нужно

6) ExcelUserService.64 а если будет какое-то другое исключение?

2024-10-28 12:35 UTC, kenpxrk1 commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +        String filename = "Отчет по пользователям. Дата: "
возможно стоит вынести создание имени файла и энкодер в отдельные методы? Например в метод по генерации имени файла можно передавать только часть названия (отчет по пользователям) чтобы его можно было юзать для других отчетов в сервисе + будет более читаемый паблик метод

2024-10-28 15:48 UTC, Belaquaa requested changes

2024-10-28 15:48 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/controller/UserReportController.java
>      private final ExcelService excelService;
@Qualifier("ExcelUserService")
private final ExcelService excelService;

И оставить @RequiredArgsConstructor

2024-10-28 15:48 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/controller/UserReportController.java
> +@RequestMapping("v1/api/users/report")
хмм, я бы сделал просто v1/api здесь и уже
@GetMapping("/users/report")

2024-10-28 15:48 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +            if (value == null) {
сделать через Objects.isNull(value)
так даже можно будет красивенько тернарным оператором сделать

2024-10-28 15:50 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/controller/UserReportController.java
>      private final ExcelService excelService;
ну и в целом интерфейс я бы назвал типа "ReportService", т.к. ты потом можешь выгружать в .csv, и тут уже название эксель не подходит

2024-10-28 15:52 UTC, SashaTyutyaev commented on src/main/java/lissa/trading/statisticsService/controller/UserReportController.java
>      private final ExcelService excelService;
А нет вероятности что ломбок начудит как то с @Qualifier

2024-10-28 15:58 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/controller/UserReportController.java
>      private final ExcelService excelService;
не, он переносит аннотации полей в конструктор

2024-10-28 15:59 UTC, SashaTyutyaev commented on src/main/java/lissa/trading/statisticsService/controller/UserReportController.java
>      private final ExcelService excelService;
А идея мне писала что нет, вот я написал сам его

2024-10-28 16:19 UTC, Belaquaa commented on src/main/java/lissa/trading/statisticsService/controller/UserReportController.java
>      private final ExcelService excelService;
Вот причина такого поведения идеи: https://www.jetbrains.com.cn/en-us/help/inspectopedia/SpringQualifierCopyableLombok.html
Вот ветка на стаковерфлоу про квалифаер с ломбоком: https://stackoverflow.com/questions/38549657/is-it-possible-to-add-qualifiers-in-requiredargsconstructoronconstructor#comment99739644_50287955
И статейка: https://ath3nd.wordpress.com/2018/12/13/spring-lombok-or-injection-just-became-a-bit-easier-part-2-of-2/

Чтобы так юзать аннотацию, тебе может понадобится добавить в lombok.config строчки:
lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Qualifier
lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Value
а может и не понадобится, где-то пишут, что это есть по умолчанию

2024-10-28 17:13 UTC, SashaTyutyaev commented on src/main/java/lissa/trading/statisticsService/service/excel/user/ExcelUserService.java
> +            if (value == null) {
через тернарный не получится, видимо, потому что там разные типы у всех. Я попробовал, не получилось

2024-10-29 06:01 UTC, merged